name: 'my first container action'
description: 'A cloud guru'
author: 'Dm Bichko'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: ' Test Awesome Guru'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
